# .github/workflows/crime_pipeline.yml
name: Crime Data Pipeline

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-crime-data:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: crime_data
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libpq-dev
        sudo apt-get install -y python3-tk  # Required for matplotlib
        sudo apt-get install -y libfreetype6-dev  # Required for matplotlib fonts

    - name: Install dependencies
      run: |
        mkdir -p images
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data pipeline
      env:
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python main.py

    - name: Generate report
      env:
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
      run: |
        # Set matplotlib to use Agg backend for headless environments
        export MPLBACKEND=Agg
        python analyze_crime_data.py

    - name: Export data for Tableau
      env:
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
      run: |
        python export_for_tableau.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/* tableau_data/*
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update crime data reports [skip ci]" && git push)
